name: release-playctl

on:
  push:
    tags: ["playctl-v*"]

permissions:
  contents: write

concurrency:
  group: release-playctl-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/rust-release.yml
    with:
      crate-path: playctl
      bin-name: playctl
      tag: ${{ github.ref_name }}
